### ISSUE TITLE
Other formats?

### ISSUE THREAD

**Issue by onyx-blackbird** [0xC0000054/pdn-image-tiling-filetype#1]
I just found this nice plugin and I was wondering if it would be possible choose different file types. As I work in web, webp would be a nice format: https://developers.google.com/speed/webp
paint.net supports it so I would assume it should be possible to allow the selection of the output format.

**Comment by 0xC0000054** [comment]
>  paint.net supports it so I would assume it should be possible to allow the selection of the output format.

Paint.NET does not allow plugins to use the built-in FileTypes, I am limited to what GDI+ supports.
